
-- Gloo Rush global arcade leaderboard
-- Run this once in the Supabase SQL Editor for the same project used by the Data Center.

create table if not exists public.gloo_rush_scores (
  id bigint generated by default as identity primary key,
  initials text not null check (initials ~ '^[A-Z0-9]{3}$'),
  score integer not null check (score between 0 and 100000000),
  enemies integer not null default 0 check (enemies between 0 and 100000),
  run_seconds integer not null default 0 check (run_seconds between 0 and 86400),
  level_reached smallint not null default 1 check (level_reached between 1 and 5),
  result text not null default 'run' check (result in ('run', 'gameover', 'victory')),
  character text not null check (character in ('kelly', 'tatsuya', 'orion', 'hayato')),
  user_id uuid null default auth.uid(),
  created_at timestamptz not null default now()
);

create index if not exists gloo_rush_scores_ranking_idx
  on public.gloo_rush_scores (score desc, level_reached desc, run_seconds asc, created_at asc);

alter table public.gloo_rush_scores enable row level security;

-- Everyone can read the shared leaderboard.
drop policy if exists "Public can view Gloo Rush scores" on public.gloo_rush_scores;
create policy "Public can view Gloo Rush scores"
  on public.gloo_rush_scores
  for select
  to anon, authenticated
  using (true);

-- Direct client inserts stay blocked. Scores are submitted only through the validated RPC below.
revoke insert, update, delete on public.gloo_rush_scores from anon, authenticated;
grant select on public.gloo_rush_scores to anon, authenticated;

drop function if exists public.submit_gloo_rush_score(text, integer, integer, integer, integer, text, text);
create function public.submit_gloo_rush_score(
  p_initials text,
  p_score integer,
  p_enemies integer,
  p_run_seconds integer,
  p_level_reached integer,
  p_result text,
  p_character text
)
returns table (score_id bigint, rank_position bigint)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_initials text := upper(regexp_replace(coalesce(p_initials, ''), '[^A-Z0-9]', '', 'g'));
  v_id bigint;
begin
  if auth.uid() is null then
    raise exception 'You must be signed in to submit a score';
  end if;
  if exists (
    select 1 from public.gloo_rush_scores
    where user_id = auth.uid()
      and created_at > now() - interval '20 seconds'
  ) then
    raise exception 'Please wait before submitting another score';
  end if;
  if length(v_initials) <> 3 then
    raise exception 'Initials must contain exactly 3 letters or numbers';
  end if;
  if p_score is null or p_score < 0 or p_score > 100000000 then
    raise exception 'Score is outside the accepted range';
  end if;
  if p_enemies is null or p_enemies < 0 or p_enemies > 100000 then
    raise exception 'Enemy count is outside the accepted range';
  end if;
  if p_run_seconds is null or p_run_seconds < 0 or p_run_seconds > 86400 then
    raise exception 'Run time is outside the accepted range';
  end if;
  if p_level_reached is null or p_level_reached not between 1 and 5 then
    raise exception 'Level reached must be between 1 and 5';
  end if;
  if p_result not in ('run', 'gameover', 'victory') then
    raise exception 'Invalid result';
  end if;
  if p_character not in ('kelly', 'tatsuya', 'orion', 'hayato') then
    raise exception 'Invalid character';
  end if;

  insert into public.gloo_rush_scores (
    initials, score, enemies, run_seconds, level_reached, result, character, user_id
  ) values (
    v_initials, p_score, p_enemies, p_run_seconds, p_level_reached, p_result, p_character, auth.uid()
  )
  returning id into v_id;

  return query
  select
    v_id,
    1 + count(*)::bigint
  from public.gloo_rush_scores s
  where
    s.score > p_score
    or (s.score = p_score and s.level_reached > p_level_reached)
    or (s.score = p_score and s.level_reached = p_level_reached and s.run_seconds < p_run_seconds)
    or (s.score = p_score and s.level_reached = p_level_reached and s.run_seconds = p_run_seconds and s.id < v_id);
end;
$$;

revoke all on function public.submit_gloo_rush_score(text, integer, integer, integer, integer, text, text) from public;
grant execute on function public.submit_gloo_rush_score(text, integer, integer, integer, integer, text, text) to authenticated;
