'use strict';
const SAVE_KEY = 'breakpoint_survivor_v1';
const app = document.getElementById('app');
const freshRpg=()=>({level:1,xp:0,points:0,credits:0,items:[],skills:{power:0,vitality:0,recon:0},positions:{},unlocked:0});
const fresh = () => ({node:'drop',hp:60,maxHp:60,medkits:1,trust:0,evidence:0,flags:[],log:[],combat:null,mode:'story',sound:false,rpg:freshRpg()});
let state;
try { const parsed=JSON.parse(localStorage.getItem(SAVE_KEY)); state=parsed && typeof parsed.node==='string' && Number.isFinite(parsed.hp) ? {...fresh(),...parsed} : fresh(); } catch { state=fresh(); }
if(state.mode==='combat'||state.mode==='defeat'){state.mode='story';state.combat=null}
state.rpg={...freshRpg(),...state.rpg,skills:{...freshRpg().skills,...state.rpg?.skills}};
if(state.node==='afterPatrol')state.rpg.unlocked=Math.max(state.rpg.unlocked,1);
if(state.node==='afterDrone'||state.node==='moco'||state.node==='reveal'||state.node==='ally'||state.node==='independent')state.rpg.unlocked=Math.max(state.rpg.unlocked,2);
if(['land','afterPatrol','afterDrone'].includes(state.node)&&state.mode==='story')state.mode='world';
let arenaInstance=null,worldInstance=null,fireInterval=null;
let worldDialogActions=[];
const save=()=>{try{localStorage.setItem(SAVE_KEY,JSON.stringify(state));}catch{}};
const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let audioContext;
function sound(freq=440){
 if(!state.sound)return;
 try{audioContext ||= new (window.AudioContext||window.webkitAudioContext)();const oscillator=audioContext.createOscillator(),gain=audioContext.createGain(),now=audioContext.currentTime;oscillator.type='triangle';oscillator.frequency.setValueAtTime(freq,now);gain.gain.setValueAtTime(.035,now);gain.gain.exponentialRampToValueAtTime(.001,now+.12);oscillator.connect(gain).connect(audioContext.destination);oscillator.start(now);oscillator.stop(now+.12);}catch{}
}
const has=f=>state.flags.includes(f);
const sectorOf=id=>({land:0,afterPatrol:1,afterDrone:2})[id];
const nextXp=level=>level===1?50:level===2?130:240+(level-3)*130;
function gainXp(amount){state.rpg.xp+=amount;let leveled=false;while(state.rpg.xp>=nextXp(state.rpg.level)){state.rpg.level++;state.rpg.points++;state.maxHp+=5;state.hp=Math.min(state.maxHp,state.hp+5);leveled=true}if(leveled)worldInstance?.notice(`LEVEL ${state.rpg.level}! Spend a skill point in Skills.`);save();return leveled}
function addItem(name){if(!state.rpg.items.includes(name))state.rpg.items.push(name)}
function worldQuest(){const s=sectorOf(state.node);if(s===0)return state.rpg.unlocked>0?'Patrol cleared. Search for missed supplies or travel onward.':has('radio')?'Reach the patrol gate and clear the contractors.':'Find and inspect the patrol radio.';if(s===1)return state.rpg.unlocked>1?'Hunter defeated. Search for missed supplies or travel onward.':has('courier')?'Reach the quarry gate and stop the relay hunter.':'Find the wounded courier and decide how to help.';return has('terminal')?'Reach the signal gate and confront Moco.':'Decrypt the subject terminal.'}
function gateReady(){const s=sectorOf(state.node);if(s<state.rpg.unlocked)return true;if(s===0)return has('radio');if(s===1)return has('courier');return has('terminal')}
const chapters=['THE DROP','THE PURSUIT','THE SIGNAL','THE EYE'];
const nodes={
 drop:{chapter:0,title:'The Drop',location:'BERMUDA / UNKNOWN SECTOR',art:'city',panels:['The transport doors open over a sleeping island.','A red light sweeps the seats. Every wristband answers—except yours.','Then the floor disappears.'],speaker:'UNKNOWN VOICE',text:'“Survivor 031. Your signal has been removed from the roster. Do not trust the extraction beacon.”',choices:[{title:'Follow the warning',hint:'Land beyond the beacon. Start with cover and a quieter route.',to:'land',effect:{flags:['cautious'],evidence:1}},{title:'Go straight for the beacon',hint:'A faster route with a useful supply cache.',to:'land',effect:{medkits:1,flags:['bold']}}]},
 land:{chapter:0,title:'No Safe Landing',location:'BERMUDA / OUTER RIDGE',art:'fire',panels:['You hit the ground. A distant tower pulses orange.','An armored patrol moves through the grass beneath it.','On your wrist: a serial number under scratched glass. SUBJECT 031.'],speaker:'YOU',text:'“I don’t remember boarding that plane. I do remember they wanted this number hidden.”',choices:[{title:'Search the crashed supply case',hint:'Find a field patch. The patrol gets closer.',to:'patrol',effect:{medkits:1,flags:['supply']}},{title:'Shadow the patrol',hint:'Record a transmission; gain evidence.',to:'patrol',effect:{evidence:1,flags:['transmission']}}]},
 patrol:{chapter:0,title:'First Contact',location:'BERMUDA / RELAY APPROACH',art:'city',panels:['Two searchlights cross the road.','A contractor spots the broken wristband.','“That one is off the roster.”'],speaker:'PATROL LEAD',text:'“Subject 031. Hands where I can see them.”',battle:'patrolFight'},
 afterPatrol:{chapter:1,title:'The Pursuit',location:'BERMUDA / SERVICE ROAD',art:'fire',panels:['The patrol radio hisses with orders to recover you alive.','Behind the wreck: a wounded courier clutches a data drive.','Above you, a drone changes course.'],speaker:'COURIER',text:'“They weren’t counting survivors. They were counting reactions. Take this before they wipe it.”',choices:[{title:'Carry the courier to shelter',hint:'Gain trust. The drone closes the distance.',to:'drone',effect:{trust:2,flags:['rescued']}},{title:'Secure the drive first',hint:'Gain a clean copy of the experiment log.',to:'drone',effect:{evidence:2,flags:['drive']}}]},
 drone:{chapter:1,title:'The Relay Hunter',location:'BERMUDA / OLD QUARRY',art:'lab',panels:['A machine drops through the rain. Its lens finds the scar on your wrist.','“RECOVERY AUTHORIZED.”','The only exit is a narrow maintenance trench.'],speaker:'YOU',text:'“If I break its link, I can get through.”',battle:'droneFight'},
 afterDrone:{chapter:2,title:'A Signal in the Static',location:'BERMUDA / ABANDONED STATION',art:'signal',panels:['In the drone memory: footage of your drop, tagged before the plane took off.','A second signal cuts through the recording. Someone is watching the watchers.','A turquoise reticle settles over your chest.'],speaker:'DISTORTED VOICE',text:'“Put down the drive. You’re carrying a Horizon marker.”',choices:[{title:'Show the stolen records',hint:'Present what you learned. The stranger may listen.',to:'moco',effect:{evidence:1,trust:1,flags:['shared']}},{title:'Keep the records hidden',hint:'Protect your leverage. Face a colder reception.',to:'moco',effect:{flags:['withheld']}}]},
 moco:{chapter:2,title:'The Eye of the Digital World',location:'BERMUDA / SIGNAL STATION',art:'moco',panels:['Every screen goes dark. Then they all show the same eye.','The stranger slips between the relay towers. Your equipment starts reporting your location.','She is too far ahead to overpower. Endure the pursuit and prove you are no agent.'],speaker:'MOCO',text:'“Four moves. That’s how long you have to convince me.”',battle:'mocoFight'},
 reveal:{chapter:3,title:'The Erased File',location:'BERMUDA / SIGNAL STATION',art:'subject',panels:['The signal breaks. Moco pulls your wristband into her private network.','An employee file opens, then vanishes. A subject file remains.','SUBJECT 031 / RECOVERY PRIORITY: ABSOLUTE.'],speaker:'MOCO',text:'“You weren’t sent to monitor this operation. You were the reason it started.”',choices:[{title:'Give Moco the whole file',hint:'Take the first step toward an alliance.',to:'ally',effect:{trust:2,flags:['allied']}},{title:'Keep a copy for yourself',hint:'Cooperate cautiously and preserve your own lead.',to:'independent',effect:{evidence:1,flags:['independent']}}]},
 ally:{chapter:3,title:'An Uneasy Alliance',location:'BERMUDA / EXIT ROUTE',art:'moco',panels:['Moco routes a false identity into the search grid.','The name on the recovered file is yours. The last page is encrypted.','Far away, an extraction craft changes destination.'],speaker:'MOCO',text:'“Come with me. Someone in the Mambas may know who erased you.”',ending:true},
 independent:{chapter:3,title:'The Hidden Copy',location:'BERMUDA / EXIT ROUTE',art:'eye',panels:['You duplicate the record before Moco seals the network.','She notices. She does not stop you.','A new message appears on your private copy: WE KNOW WHAT YOU TOOK.'],speaker:'MOCO',text:'“Keep your secrets for now. Just don’t let Horizon find them first.”',ending:true}
};
const enemies={
 patrolFight:{name:'HORIZON CONTRACTOR',tag:'LV. 06 / MINION',hp:32,damage:7,turns:0,objective:'Defeat the contractor',next:'afterPatrol',art:'city',intro:'Watch the enemy’s next move. Cover halves incoming damage; Aim powers your next shot.'},
 droneFight:{name:'RELAY HUNTER',tag:'LV. 12 / ELITE MACHINE',hp:46,damage:9,turns:0,objective:'Break the drone',next:'afterDrone',art:'lab',intro:'Its shield absorbs most shots. Scan to expose its relay before firing.',shielded:true},
 mocoFight:{name:'MOCO',tag:'LV. ?? / SURVIVAL ENCOUNTER',hp:99,damage:10,turns:4,objective:'Survive four rounds',next:'reveal',art:'moco',intro:'Moco cannot be defeated in this encounter. Survive four turns; the evidence you gathered shapes her response.'}
};
function apply(effect={}){if(effect.medkits)state.medkits+=effect.medkits;if(effect.evidence)state.evidence+=effect.evidence;if(effect.trust)state.trust+=effect.trust;for(const f of effect.flags||[])if(!has(f))state.flags.push(f);}
function go(id){if(!nodes[id])return;state.node=id;state.combat=null;state.mode=sectorOf(id)!==undefined?'world':'story';if(id==='afterPatrol')state.rpg.unlocked=Math.max(state.rpg.unlocked,1);if(id==='afterDrone')state.rpg.unlocked=Math.max(state.rpg.unlocked,2);if(id==='reveal')state.hp=Math.max(state.hp,30);save();render();window.scrollTo(0,0)}
function choose(index){const c=nodes[state.node]?.choices?.[index];if(!c)return;sound(525);apply(c.effect);state.log.push(`${nodes[state.node].title}: ${c.title}`);go(c.to)}
function startBattle(){const def=enemies[nodes[state.node]?.battle];if(!def)return;state.hp=state.maxHp;state.combat={id:nodes[state.node].battle,medkitsAtStart:state.medkits,playerHpAtStart:state.hp};state.mode='arena';save();render()}
function intent(c,def){if(def===enemies.mocoFight){return c.rounds===2?'SIGNAL JAM · Your next action loses its aim bonus':'TRACKING SHOT · '+(def.damage+(c.rounds%2?2:0))+' damage'}if(def===enemies.droneFight&&c.turn%3===0)return 'OVERCHARGE · 14 damage';if(c.turn%3===0)return 'HEAVY SHOT · '+(def.damage+4)+' damage';return 'BURST FIRE · '+def.damage+' damage'}
function action(kind){const c=state.combat;if(!c||state.mode!=='combat')return;const def=enemies[c.id];if(kind==='heal'&&state.medkits<1)return;sound(kind==='shoot'?180:kind==='scan'?640:360);let msg='';let damage=0;
 if(kind==='shoot'){damage=9+(c.aim?10:0)+(c.exposed?7:0);if(def.shielded&&!c.exposed)damage=Math.ceil(damage/3);c.hp=Math.max(0,c.hp-damage);msg=`You fire for ${damage} damage${def.shielded&&!c.exposed?' against the shield':''}.`;c.aim=false;if(!def.shielded)c.exposed=false;}
 else if(kind==='aim'){c.aim=true;msg='You steady your shot. Your next attack gains 10 damage.';}
 else if(kind==='cover'){c.cover=true;msg='You move behind cover. The next hit is reduced.';}
 else if(kind==='scan'){c.scanUsed=true;if(def.shielded)c.exposed=true;msg=def.shielded?'Relay located. The shield stays offline; shots gain 7 damage.':'Your scan traces the attacker’s signal. The hidden subject file starts to surface.';}
 else if(kind==='heal'){if(state.medkits<1)return;state.medkits--;const old=state.hp;state.hp=Math.min(state.maxHp,state.hp+24);msg=`Field patch restores ${state.hp-old} HP.`;}
 else return;
 if(def.turns===0&&c.hp<=0){win(msg);return;}
 const jam=def===enemies.mocoFight&&c.rounds===2;
 if(jam){c.aim=false;msg+=' Moco jams your targeting feed.';}else{const base=def===enemies.droneFight&&c.turn%3===0?14:def.damage+(def===enemies.mocoFight&&c.rounds%2?2:0)+(def!==enemies.mocoFight&&def!==enemies.droneFight&&c.turn%3===0?4:0);const incoming=c.cover?Math.max(1,Math.ceil(base/3)):base;state.hp=Math.max(0,state.hp-incoming);msg+=` ${def.name} hits for ${incoming} damage${c.cover?' through cover':''}.`;}
 c.cover=false;c.rounds++;c.turn++;c.message=msg;
 if(state.hp<=0){state.mode='defeat';save();render();return;}
 if(def.turns>0&&c.rounds>=def.turns){win(msg);return;}
 save();render();}
function win(msg){const c=state.combat,def=enemies[c.id];if(c.id==='mocoFight'){state.trust+=c.scanUsed?1:0;if(state.evidence>=3)state.trust+=1;}else{state.hp=Math.min(state.maxHp,state.hp+10);}state.log.push(`${def.name}: ${def.objective} complete`);state.node=def.next;state.combat=null;state.mode='story';save();render();window.scrollTo(0,0)}
function retry(){const c=state.combat;if(!c)return;const id=c.id;state.hp=c.playerHpAtStart;state.medkits=c.medkitsAtStart;state.combat=null;state.mode='story';state.node=Object.keys(nodes).find(key=>nodes[key].battle===id)||'patrol';save();startBattle()}
function panel(text,art,n){return `<div class="panel"><div class="scene-art art-${esc(art)}" aria-hidden="true"></div><span class="panel-label">0${n}</span><div class="panel-caption">${esc(text)}</div></div>`}
function sidebar(){return `<aside class="aside" aria-label="Survivor dossier"><div class="aside-box"><span class="kicker">SUBJECT 031</span><h3>Survivor status</h3><div class="stat"><div class="stat-top"><span>VITALS</span><span>${state.hp} / ${state.maxHp}</span></div><div class="meter cyan-meter"><span style="width:${clamp(state.hp/state.maxHp*100,0,100)}%"></span></div></div><div class="stat"><div class="stat-top"><span>MOCO TRUST</span><span>${clamp(state.trust,0,6)} / 6</span></div><div class="meter"><span style="width:${clamp(state.trust/6*100,0,100)}%"></span></div></div><p>FIELD PATCHES ${state.medkits} &nbsp;·&nbsp; EVIDENCE ${state.evidence}</p></div><div class="aside-box"><span class="kicker">CASE FILE</span><h3>What you know</h3><ul class="aside-list"><li><strong>01 / The wristband</strong><br>Subject 031 was removed from the public roster.</li>${state.evidence>0?'<li><strong>02 / The signal</strong><br>Someone tracked the drop before it happened.</li>':''}${has('rescued')?'<li><strong>03 / The courier</strong><br>You pulled the courier to safety.</li>':''}${has('drive')?'<li><strong>03 / The drive</strong><br>You kept the experiment log intact.</li>':''}${state.log.map(x=>`<li>✓ ${esc(x)}</li>`).join('')}</ul></div><button class="dossier-button" type="button" data-command="dossier">OPEN LORE DOSSIER ↗</button><p class="notice">Story events and Subject 031 are original fiction. The dossier marks the official lore used as a foundation.</p></aside>`}
function chapterBar(n){return `<div class="chapter-bar"><span>CHAPTER 0${n+1} / 04 · ${chapters[n]}</span><div class="progress" aria-label="Chapter ${n+1} of four">${chapters.map((_,i)=>`<i class="${i<=n?'on':''}"></i>`).join('')}</div></div>`}
function story(){const n=nodes[state.node]||nodes.drop;app.innerHTML=`<div class="layout"><section class="main-col">${chapterBar(n.chapter)}<div class="chapter-heading"><span class="kicker">${esc(n.location)}</span><h2>${esc(n.title)}</h2><p>VOLUME I · THE SURVIVOR</p></div><div class="panels">${n.panels.map((p,i)=>panel(p,i===1?'signal':i===2?'eye':n.art,i+1)).join('')}</div><div class="dialogue"><div class="speaker">${esc(n.speaker)}</div><p>${esc(n.text)}</p></div>${n.battle?`<button class="button" type="button" data-command="start">ENTER ENCOUNTER <strong>↗</strong></button>`:n.ending?`<div class="result"><span class="pill orange">END OF PLAYABLE CHAPTER</span><h2>TO BE CONTINUED.</h2><p>Your path: ${has('allied')?'Moco has your complete file.':'You kept a private copy of the file.'} ${has('rescued')?'The courier survived because of you.':'You prioritized the experiment data.'} Trust: ${state.trust}. Evidence: ${state.evidence}.</p><p>Next volume: the Mambas, the erased subject records, and the first real answer to who put you on the island.</p><button class="button secondary" type="button" data-command="dossier">EXPLORE THE LORE DOSSIER ↗</button></div>`:`<div class="choices">${n.choices.map((c,i)=>`<button class="choice" type="button" data-choice="${i}"><span class="choice-no">0${i+1}</span><span class="choice-text"><strong>${esc(c.title)}</strong><small>${esc(c.hint)}</small></span><span class="choice-arrow">↗</span></button>`).join('')}</div>`}</section>${sidebar()}</div>`}
function combat(){const c=state.combat,def=enemies[c.id],moco=def.turns>0;app.innerHTML=`<div class="layout"><section class="main-col">${chapterBar(nodes[state.node].chapter)}<div class="chapter-heading"><span class="kicker">TACTICAL ENCOUNTER · TURN ${c.turn}</span><h2>${esc(def.objective)}</h2><p>${esc(def.tag)}</p></div><div class="combat-shell"><div class="combat-head"><div><span class="kicker">ENCOUNTER 0${['patrolFight','droneFight','mocoFight'].indexOf(c.id)+1}</span><h3>${esc(def.name)}</h3><p>${esc(def.intro)}</p></div><span class="pill ${moco?'cyan':'orange'}">${moco?`${c.rounds}/4 ROUNDS`:`${c.hp}/${def.hp} HP`}</span></div><div class="arena"><div class="fighter"><div class="scene-art art-fire" aria-hidden="true"></div><span class="pill cyan">SURVIVOR</span><h4>SUBJECT 031</h4><div class="health"><span style="width:${state.hp/state.maxHp*100}%"></span></div><div class="fighter-meta">${state.hp} / ${state.maxHp} HP · ${state.medkits} PATCHES</div></div><div class="fighter enemy"><div class="scene-art art-${esc(def.art)}" aria-hidden="true"></div><span class="pill orange">${esc(def.tag)}</span><h4>${esc(def.name)}</h4><div class="health"><span style="width:${c.hp/def.hp*100}%"></span></div><div class="fighter-meta">${moco?'SURVIVE / DO NOT ATTACK TO WIN':`${c.hp} / ${def.hp} HP`}</div></div></div><div class="intent"><strong>NEXT INTENT:</strong> ${esc(intent(c,def))}</div><div class="combat-log" role="status">${esc(c.message)}</div><div class="action-grid"><button class="action" data-action="shoot" type="button"><strong>01 · FIRE</strong><span>${moco?'Suppress the pursuit.':'9 damage; Aim and Scan increase it.'}</span></button><button class="action" data-action="aim" type="button"><strong>02 · AIM</strong><span>Next shot +10 damage. ${c.aim?'READY':''}</span></button><button class="action" data-action="cover" type="button"><strong>03 · TAKE COVER</strong><span>Reduce the next incoming hit to one third.</span></button><button class="action" data-action="scan" type="button"><strong>04 · SCAN</strong><span>${def.shielded?'Disable its shield; shots gain 7 damage.':'Trace the signal and uncover evidence.'}</span></button><button class="action" data-action="heal" type="button" ${state.medkits<1?'disabled':''}><strong>05 · FIELD PATCH × ${state.medkits}</strong><span>Restore up to 24 HP. Uses your turn.</span></button></div><div class="battle-info">Each action advances one enemy turn. Your progress saves automatically.</div></div></section>${sidebar()}</div>`}
function refreshWorldHud(){const set=(id,value)=>{const el=document.getElementById(id);if(el)el.textContent=value};set('worldLevel',`LV ${state.rpg.level}`);set('worldXp',`${state.rpg.xp} / ${nextXp(state.rpg.level)} XP`);set('worldQuest',worldQuest());set('worldCredits',`${state.rpg.credits} CREDITS`);set('worldSupplies',`${state.medkits} PATCHES`);set('worldSkills',`${state.rpg.points} POINT${state.rpg.points===1?'':'S'}`);set('worldSideQuest',worldQuest());if(worldInstance)worldInstance.config.gateOpen=gateReady()}
function worldModal(title,body,actions=[]){worldDialogActions=actions;if(worldInstance)worldInstance.paused=true;const el=document.getElementById('worldOverlay');if(!el)return;el.hidden=false;el.innerHTML=`<div class="world-dialog"><span class="kicker">FIELD INTERACTION</span><h3>${esc(title)}</h3><p>${esc(body)}</p><div class="world-dialog-actions">${actions.map((a,i)=>`<button class="choice" type="button" data-world-choice="${i}"><span class="choice-no">0${i+1}</span><span class="choice-text"><strong>${esc(a.label)}</strong><small>${esc(a.hint||'')}</small></span></button>`).join('')}<button class="button secondary small" type="button" data-command="worldClose">CLOSE</button></div></div>`}
function closeWorldModal(){const el=document.getElementById('worldOverlay');if(el){el.hidden=true;el.innerHTML=''}worldDialogActions=[];if(worldInstance)worldInstance.paused=false;refreshWorldHud()}
function worldInteract(id){
 const flag=name=>{if(!has(name))state.flags.push(name)};
 if(id==='gate'){if(!gateReady()){worldInstance?.notice(worldQuest());return}state.rpg.positions[state.node]={x:worldInstance.player.x,y:worldInstance.player.y};const s=sectorOf(state.node);if(s<state.rpg.unlocked){go(['afterPatrol','afterDrone'][s]);return}state.node=['patrol','drone','moco'][s];save();startBattle();return}
 if(id==='case'&&!has('case')){flag('case');state.medkits++;state.rpg.credits+=10;gainXp(15);worldInstance?.notice('SUPPLY CACHE: +1 patch, +10 credits, +15 XP.');}
 if(id==='radio'&&!has('radio')){flag('radio');state.evidence++;addItem('Patrol access code');gainXp(25);worldInstance?.notice('PATROL CODE RECOVERED: gate unlocked, +25 XP.');}
 if(id==='scrap'&&!has('scrap')){flag('scrap');state.rpg.credits+=25;gainXp(15);worldInstance?.notice('SALVAGE: +25 credits, +15 XP.');}
 if(id==='kit'&&!has('kit')){flag('kit');state.medkits++;state.rpg.credits+=10;gainXp(15);worldInstance?.notice('MEDICAL CACHE: +1 patch, +10 credits, +15 XP.');}
 if(['beacon','component','core'].includes(id)&&!has(id)){flag(id);addItem(`Beacon ${id==='beacon'?'casing':id==='component'?'transmitter':'power core'}`);gainXp(12);const parts=['beacon','component','core'].filter(has).length;if(parts===3&&!has('scrambler')){flag('scrambler');addItem('Signal scrambler');gainXp(35);worldInstance?.notice('SIDE QUEST COMPLETE: Signal scrambler equipped. +50 scan range.')}else worldInstance?.notice(`BEACON PART FOUND: ${parts}/3 · +12 XP.`)}
 if(id==='courier'&&!has('courier'))worldModal('Wounded courier','The courier offers a drive containing the island experiment log. What do you do?',[{label:'Carry the courier to shelter',hint:'+2 Moco trust · +30 XP',run(){flag('courier');flag('rescued');state.trust+=2;gainXp(30);worldInstance?.notice('Courier rescued. Quarry gate unlocked.')}},{label:'Secure the intact data drive',hint:'+2 evidence · Experiment log · +30 XP',run(){flag('courier');flag('drive');state.evidence+=2;addItem('Experiment log');gainXp(30);worldInstance?.notice('Drive secured. Quarry gate unlocked.')}}]);
 if(id==='trader')worldModal('Scavenger','“I can patch you up or reinforce that vest. Bring credits.”',[{label:'Field patch · 20 credits',hint:'Restores 32 HP in combat.',run(){if(state.rpg.credits<20){worldInstance?.notice('Not enough credits.');return}state.rpg.credits-=20;state.medkits++;worldInstance?.notice('Purchased one field patch.')}},{label:'Reinforced vest · 35 credits',hint:'Permanent +10 maximum HP.',run(){if(has('vest')){worldInstance?.notice('Vest already equipped.');return}if(state.rpg.credits<35){worldInstance?.notice('Not enough credits.');return}state.rpg.credits-=35;state.maxHp+=10;state.hp+=10;flag('vest');addItem('Reinforced vest');worldInstance?.notice('Reinforced vest equipped. +10 max HP.')}}]);
 if(id==='terminal'&&!has('terminal'))worldModal('Subject terminal','A hidden Horizon identifier appears. Moco is listening to the channel.',[{label:'Share the recovered record',hint:'+1 trust · +1 evidence · +30 XP',run(){flag('terminal');flag('shared');state.trust++;state.evidence++;addItem('Subject 031 file');gainXp(30);worldInstance?.notice('Record shared. Signal gate unlocked.')}},{label:'Keep a private copy',hint:'+1 evidence · +30 XP',run(){flag('terminal');flag('withheld');state.evidence++;addItem('Private subject file');gainXp(30);worldInstance?.notice('Private copy secured. Signal gate unlocked.')}}]);
 save();refreshWorldHud();
}
function openWorldPanel(type){if(type==='inventory'){worldModal('Inventory',`Equipment: ${has('vest')?'Reinforced vest (+10 HP)':'Standard field gear'}${has('scrambler')?', Signal scrambler (+50 scan range)':''}. Key items: ${state.rpg.items.join(', ')||'None yet'}. Field patches: ${state.medkits}. Credits: ${state.rpg.credits}.`);return}if(type==='journal'){worldModal('Quest journal',`Main: ${worldQuest()} Side quest: Recover three beacon parts (${['beacon','component','core'].filter(has).length}/3) to build a signal scrambler. Evidence: ${state.evidence}. Moco trust: ${state.trust}. Completed: ${state.log.join('; ')||'None yet'}.`);return}if(type==='map'){worldModal('Bermuda map','Travel to an unlocked area. Your position and collected objects are saved.',[{label:'Crash Site',hint:'Drop zone · patrol radio',run(){go('land')}},...(state.rpg.unlocked>=1?[{label:'Service Road',hint:'Courier · scavenger',run(){go('afterPatrol')}}]:[]),...(state.rpg.unlocked>=2?[{label:'Signal Outpost',hint:'Subject terminal',run(){go('afterDrone')}}]:[])]);return}worldModal('Survivor skills',`Level ${state.rpg.level} · ${state.rpg.points} available skill points. Earn XP from exploration, quests, and combat.`,[{label:`Marksmanship ${state.rpg.skills.power}/3`,hint:'+4 weapon damage per rank',run(){buySkill('power')}},{label:`Vitality ${state.rpg.skills.vitality}/3`,hint:'+10 maximum HP per rank',run(){buySkill('vitality')}},{label:`Recon ${state.rpg.skills.recon}/3`,hint:'+50 scan range per rank',run(){buySkill('recon')}}])}
function buySkill(skill){if(state.rpg.points<1){worldInstance?.notice('Earn a level to gain a skill point.');return}if(state.rpg.skills[skill]>=3){worldInstance?.notice('That skill is already maxed.');return}state.rpg.points--;state.rpg.skills[skill]++;if(skill==='vitality'){state.maxHp+=10;state.hp+=10}save();worldInstance?.notice(`${skill.toUpperCase()} UPGRADED.`)}
function worldScreen(){const sector=sectorOf(state.node);if(sector===undefined){state.mode='story';story();return}const loc=['BERMUDA / CRASH SITE','BERMUDA / SERVICE ROAD','BERMUDA / SIGNAL OUTPOST'][sector];app.innerHTML=`<div class="layout action-layout"><section class="main-col">${chapterBar(sector)}<div class="chapter-heading"><span class="kicker">EXPLORE · ${esc(loc)}</span><h2>${['The Drop Zone','The Courier','The Hidden Signal'][sector]}</h2><p>Explore, collect supplies, speak with people, and prepare for the next encounter.</p></div><div class="arena-hud rpg-hud"><div><span class="kicker">CHARACTER</span><strong id="worldLevel"></strong><small id="worldXp"></small></div><div><span class="kicker">MAIN QUEST</span><strong id="worldQuest"></strong></div><div><span class="kicker">RESOURCES</span><strong id="worldCredits"></strong><small id="worldSupplies"></small></div></div><div class="action-stage world-stage"><canvas id="worldCanvas" width="900" height="520" aria-label="Explorable top-down Bermuda area"></canvas><div class="stage-actions world-touch"><div id="worldStick" class="move-stick" aria-label="Touch movement control"><span id="worldNub"></span></div><div class="touch-buttons"><button class="world-interact" type="button" data-command="worldInteract">INTERACT</button></div></div><div id="worldOverlay" class="world-overlay" hidden></div></div><div class="world-toolbar"><button type="button" data-command="skills">SKILLS <span id="worldSkills"></span></button><button type="button" data-command="inventory">INVENTORY</button><button type="button" data-command="journal">JOURNAL</button><button type="button" data-command="map">MAP</button></div><div class="control-strip"><strong>MOVE</strong> WASD / ARROWS <strong>INTERACT</strong> E / SPACE</div></section><aside class="aside"><div class="aside-box"><span class="kicker">ACTIVE QUEST</span><h3>Survivor 031</h3><p id="worldSideQuest"></p></div><div class="aside-box"><span class="kicker">GROWTH</span><h3>Build your survivor</h3><p>Explore for XP and credits. Level up for skill points. Equipment and skills carry into fights.</p></div><button class="dossier-button" type="button" data-command="dossier">LORE DOSSIER ↗</button></aside></div>`;
 const canvas=document.getElementById('worldCanvas');worldInstance=new window.BreakpointWorld(canvas,{sector,pos:state.rpg.positions[state.node],flags:state.flags,gateOpen:gateReady(),intro:['Recover the patrol code. Optional supplies are nearby.','Find the courier. A scavenger can trade supplies.','Decrypt the terminal before confronting Moco.'][sector]},{onInteract:worldInteract,onMove(p){state.rpg.positions[state.node]={x:Math.round(p.x),y:Math.round(p.y)};save()}});refreshWorldHud();
 const stick=document.getElementById('worldStick'),nub=document.getElementById('worldNub');let pointer=null;const move=e=>{if(e.pointerId!==pointer||!worldInstance)return;const b=stick.getBoundingClientRect();let x=(e.clientX-b.left-b.width/2)/40,y=(e.clientY-b.top-b.height/2)/40,n=Math.max(1,Math.hypot(x,y));x/=n;y/=n;worldInstance.joystick={x,y};nub.style.transform=`translate(${x*29}px,${y*29}px)`};stick.addEventListener('pointerdown',e=>{pointer=e.pointerId;stick.setPointerCapture(pointer);move(e);e.preventDefault()});stick.addEventListener('pointermove',move);const end=e=>{if(e.pointerId!==pointer)return;pointer=null;if(worldInstance)worldInstance.joystick={x:0,y:0};nub.style.transform='translate(0,0)'};stick.addEventListener('pointerup',end);stick.addEventListener('pointercancel',end);
}

function arenaScreen(){
 const id=state.combat?.id,def=enemies[id];if(!def){state.mode='story';story();return}
 const mission=id==='patrolFight'?'Clear the patrol, then reach extraction.':id==='droneFight'?'Disable both relays to break the drone shield.':'Decrypt the subject file, survive 22 seconds, then escape.';
 app.innerHTML=`<div class="layout action-layout"><section class="main-col">${chapterBar(nodes[state.node].chapter)}<div class="chapter-heading"><span class="kicker">LIVE ENCOUNTER · ${esc(def.tag)}</span><h2>${esc(def.name)}</h2><p>${esc(mission)}</p></div><div class="arena-hud"><div><span class="kicker">SUBJECT 031</span><strong id="arenaHp">${state.hp} / ${state.maxHp} HP</strong></div><div><span class="kicker">OBJECTIVE</span><strong id="arenaObjective">LOCATE THE TARGET</strong></div><div><span class="kicker">SUPPLIES</span><strong id="arenaKits">${state.medkits} PATCHES</strong></div></div><div class="action-stage"><canvas id="arenaCanvas" width="900" height="520" aria-label="Top-down playable action arena"></canvas><div class="stage-actions"><div id="moveStick" class="move-stick" aria-label="Touch movement control"><span id="stickNub"></span></div><div class="touch-buttons"><button type="button" data-arena="scan">SCAN</button><button type="button" data-arena="heal">HEAL</button><button type="button" data-arena="dodge">DODGE</button><button type="button" data-arena="interact">INTERACT</button><button class="fire-button" type="button" data-arena="fire">FIRE</button></div></div></div><div class="control-strip"><strong>MOVE</strong> WASD / ARROWS <strong>AIM + FIRE</strong> MOUSE / SPACE <strong>INTERACT</strong> E <strong>PATCH</strong> F <strong>SCAN</strong> Q <strong>DODGE</strong> SHIFT</div><p class="notice">Move close to glowing relays and the exit, then press Interact. The arena restarts from its checkpoint if you leave or fall.</p></section>${sidebar()}</div>`;
 const canvas=document.getElementById('arenaCanvas');arenaInstance=new window.BreakpointArena(canvas,{id,hp:state.hp,maxHp:state.maxHp,medkits:state.medkits,attack:17+state.rpg.skills.power*4,scanRadius:265+state.rpg.skills.recon*50+(has('scrambler')?50:0)},{onHud(a){const hp=document.getElementById('arenaHp'),obj=document.getElementById('arenaObjective'),kits=document.getElementById('arenaKits');if(hp)hp.textContent=`${a.player.hp} / ${a.player.maxHp} HP`;if(obj)obj.textContent=a.objectiveText();if(kits)kits.textContent=`${a.player.medkits} PATCHES`},onShot(){sound(210)},onFinish(result){if(result.win){state.hp=Math.min(state.maxHp,result.hp+(id==='mocoFight'?0:10));state.medkits=result.medkits;state.rpg.credits+=id==='patrolFight'?35:id==='droneFight'?55:80;gainXp(id==='patrolFight'?55:id==='droneFight'?80:100);if(id==='mocoFight'){if(result.scanned)state.trust++;if(state.evidence>=3)state.trust++}state.log.push(`${def.name}: ${def.objective} complete`);go(def.next)}else{state.mode='arenaDefeat';save();render()}}});
 const stick=document.getElementById('moveStick'),nub=document.getElementById('stickNub');let stickId=null;
 function stickMove(e){if(e.pointerId!==stickId||!arenaInstance)return;const box=stick.getBoundingClientRect(),cx=box.left+box.width/2,cy=box.top+box.height/2;let x=(e.clientX-cx)/40,y=(e.clientY-cy)/40;const n=Math.max(1,Math.hypot(x,y));x/=n;y/=n;arenaInstance.joystick={x,y};nub.style.transform=`translate(${x*29}px,${y*29}px)`}
 stick.addEventListener('pointerdown',e=>{stickId=e.pointerId;stick.setPointerCapture(e.pointerId);stickMove(e);e.preventDefault()});stick.addEventListener('pointermove',stickMove);function stickEnd(e){if(e.pointerId!==stickId)return;stickId=null;if(arenaInstance)arenaInstance.joystick={x:0,y:0};nub.style.transform='translate(0,0)'}stick.addEventListener('pointerup',stickEnd);stick.addEventListener('pointercancel',stickEnd);
 app.querySelectorAll('[data-arena]').forEach(button=>button.addEventListener('pointerdown',e=>{e.preventDefault();if(!arenaInstance)return;const a=button.dataset.arena;arenaInstance.touchAim=true;if(a==='fire'){arenaInstance.shoot();clearInterval(fireInterval);fireInterval=setInterval(()=>arenaInstance?.shoot(),85)}else arenaInstance[a]?.()}));
 app.querySelectorAll('[data-arena]').forEach(button=>{const stop=()=>{clearInterval(fireInterval);fireInterval=null};button.addEventListener('pointerup',stop);button.addEventListener('pointercancel',stop);button.addEventListener('pointerleave',stop)});
}
function arenaDefeat(){const def=enemies[state.combat?.id]||enemies.patrolFight;app.innerHTML=`<div class="layout"><section class="main-col"><div class="result"><span class="kicker">ENCOUNTER FAILED</span><h2>NOT THE END.</h2><p>${esc(def.name)} forced you back. Retry from the start of this arena with the health and field patches you brought into it.</p><button class="button" data-command="retryArena" type="button">RETRY ENCOUNTER ↺</button></div></section>${sidebar()}</div>`}
function defeat(){const def=enemies[state.combat?.id]||enemies.patrolFight;app.innerHTML=`<div class="layout"><section class="main-col"><div class="result"><span class="kicker">ENCOUNTER FAILED</span><h2>NOT THE END.</h2><p>${esc(def.name)} forced you back. Retry from the beginning of this encounter with the same health and field patches you had when it started.</p><button class="button" data-command="retry" type="button">RETRY ENCOUNTER ↺</button></div></section>${sidebar()}</div>`}
function dossier(){const back=state.modeBeforeDossier||'story';app.innerHTML=`<div class="layout"><section class="main-col"><button class="back-link" data-command="back" type="button">← BACK TO CHAPTER</button><div class="chapter-heading"><span class="kicker">FIELD NOTES / CANON & ORIGINAL</span><h2>Lore dossier</h2><p>Official world facts are separated from this prototype’s original plot.</p></div><div class="dossier-grid"><div class="dossier-card"><span class="pill cyan">OFFICIAL LORE</span><h3>Moco</h3><p>A technology expert who joined Horizon, discovered its wrongdoing, erased her public identity, and went into hiding to stop its plans.</p></div><div class="dossier-card"><span class="pill cyan">OFFICIAL LORE</span><h3>Steffie & the Mambas</h3><p>Horizon threatened Steffie with experimentation. Moco saved her, and Steffie found the Mambas, a rebel force.</p></div><div class="dossier-card"><span class="pill cyan">OFFICIAL LORE</span><h3>Rampage vs Horizon</h3><p>Garena frames Rampage and Horizon as opponents. Horizon’s forces conducted genetic experiments involving technology and human bodies.</p></div><div class="dossier-card"><span class="pill orange">ORIGINAL STORY</span><h3>Subject 031</h3><p>The erased survivor, the island recovery operation, courier, relay hunter, dialogue, and encounter levels are written for Breakpoint. They are not official Free Fire canon.</p></div></div><div class="source-links"><strong>Official sources:</strong><br><a href="https://ff.garena.com/en/chars/433" target="_blank" rel="noopener noreferrer">Garena · Moco biography ↗</a><br><a href="https://ff.garena.com/en/chars/150" target="_blank" rel="noopener noreferrer">Garena · Steffie biography ↗</a><br><a href="https://ff.garena.com/en/article/1234/" target="_blank" rel="noopener noreferrer">Garena · Rampage: Finale ↗</a></div><p class="notice">Free Fire, its characters, and related names belong to Garena. This noncommercial fan prototype is not endorsed by or affiliated with Garena. No official game art or assets are included.</p></section>${sidebar()}</div>`}
function intro(){const resume=state.node!=='drop'||state.mode==='combat'||state.mode==='defeat'||state.mode==='arena'||state.mode==='arenaDefeat';app.innerHTML=`<div class="intro"><div class="intro-copy"><span class="kicker">AN ACTION RPG IN AN INTERACTIVE UNIVERSE</span><h1>YOU WERE<br><em>NEVER</em><br>ON THE LIST.</h1><p>Explore Bermuda as Subject 031. Follow quests, gather evidence, loot supplies, develop your skills, and fight through action encounters. Your choices shape how Moco receives you.</p><div class="intro-actions"><button class="button" data-command="begin" type="button">${resume?'CONTINUE CHAPTER':'BEGIN CHAPTER 01'} <strong>↗</strong></button><button class="button secondary" data-command="dossier" type="button">LORE DOSSIER ↗</button></div><div class="intro-notes"><span>◈ THREE EXPLORABLE ZONES</span><span>◈ LEVELS & SKILLS</span><span>◈ AUTOSAVE</span></div></div><div class="cover"><div class="scene-art art-city" aria-hidden="true"></div><span class="stamp">ISSUE 001</span><div class="cover-title"><small>AN ACTION RPG WITH COMIC STORY BEATS</small>THE<br>SURVIVOR</div></div></div>`}
function render(){clearInterval(fireInterval);fireInterval=null;if(arenaInstance){arenaInstance.destroy();arenaInstance=null}if(worldInstance){worldInstance.destroy();worldInstance=null}if(state.mode==='intro')intro();else if(state.mode==='world')worldScreen();else if(state.mode==='arena'&&state.combat)arenaScreen();else if(state.mode==='arenaDefeat'&&state.combat)arenaDefeat();else if(state.mode==='combat'&&state.combat)combat();else if(state.mode==='defeat'&&state.combat)defeat();else if(state.mode==='dossier')dossier();else story()}
app.addEventListener('click',e=>{const choice=e.target.closest('[data-choice]');if(choice){choose(Number(choice.dataset.choice));return}const worldChoice=e.target.closest('[data-world-choice]');if(worldChoice){const selected=worldDialogActions[Number(worldChoice.dataset.worldChoice)];selected?.run();save();closeWorldModal();return}const actionBtn=e.target.closest('[data-action]');if(actionBtn){action(actionBtn.dataset.action);return}const cmd=e.target.closest('[data-command]')?.dataset.command;if(!cmd)return;if(cmd==='begin'){state.mode=state.combat?(state.combat.turn?'combat':'arena'):sectorOf(state.node)!==undefined?'world':'story';save();render()}if(cmd==='start')startBattle();if(cmd==='retry')retry();if(cmd==='retryArena'){state.hp=state.combat.playerHpAtStart;state.medkits=state.combat.medkitsAtStart;state.mode='arena';save();render()}if(cmd==='worldInteract')worldInstance?.interact();if(cmd==='worldClose')closeWorldModal();if(['skills','inventory','journal','map'].includes(cmd))openWorldPanel(cmd);if(cmd==='dossier'){state.modeBeforeDossier=state.mode;state.mode='dossier';render();window.scrollTo(0,0)}if(cmd==='back'){state.mode=state.modeBeforeDossier||'story';render()}});
document.getElementById('resetBtn').addEventListener('click',()=>{if(!confirm('Start a new game? This replaces your autosave.'))return;state=fresh();state.mode='intro';save();render()});
document.getElementById('audioBtn').addEventListener('click',e=>{state.sound=!state.sound;e.currentTarget.textContent=state.sound?'♫ ON':'♫ OFF';save()});
document.getElementById('audioBtn').textContent=state.sound?'♫ ON':'♫ OFF';
if(state.mode==='story'&&state.node==='drop'&&!localStorage.getItem(SAVE_KEY))state.mode='intro';
render();
