'use strict';
window.BreakpointWorld = class BreakpointWorld {
  constructor(canvas, config, hooks) {
    this.canvas=canvas;this.ctx=canvas.getContext('2d');this.config=config;this.hooks=hooks;
    this.sector=config.sector;this.player={x:config.pos?.x??105,y:config.pos?.y??270,r:15};
    this.width=900;this.height=520;this.keys=new Set();this.joystick={x:0,y:0};this.facing=0;this.elapsed=0;this.last=0;this.running=true;this.paused=false;this.message='';this.messageTime=0;this.saveTime=0;
    this.walls=this.sector===0?[{x:285,y:82,w:102,h:77},{x:397,y:332,w:120,h:75}]:this.sector===1?[{x:325,y:80,w:115,h:72},{x:565,y:334,w:105,h:70}]:[{x:250,y:92,w:88,h:100},{x:570,y:318,w:110,h:72}];
    this.objects=this.sector===0?[{id:'case',x:230,y:394,type:'crate',label:'SUPPLY CACHE'},{id:'radio',x:508,y:163,type:'terminal',label:'PATROL RADIO'},{id:'beacon',x:674,y:405,type:'crate',label:'BEACON PART 1'},{id:'gate',x:809,y:258,type:'gate',label:'PATROL GATE'}]:this.sector===1?[{id:'trader',x:220,y:130,type:'npc',label:'SCAVENGER'},{id:'courier',x:468,y:252,type:'npc',label:'WOUNDED COURIER'},{id:'scrap',x:731,y:392,type:'crate',label:'SALVAGE CRATE'},{id:'component',x:528,y:420,type:'crate',label:'BEACON PART 2'},{id:'gate',x:809,y:258,type:'gate',label:'QUARRY GATE'}]:[{id:'kit',x:200,y:408,type:'crate',label:'MEDICAL CACHE'},{id:'terminal',x:432,y:150,type:'terminal',label:'SUBJECT TERMINAL'},{id:'core',x:727,y:413,type:'crate',label:'BEACON PART 3'},{id:'gate',x:809,y:258,type:'gate',label:'SIGNAL GATE'}];
    this.unsubs=[];this.listen(window,'keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'].includes(e.code))e.preventDefault();this.keys.add(e.code);if(!e.repeat&&(e.code==='KeyE'||e.code==='Space'))this.interact()});this.listen(window,'keyup',e=>this.keys.delete(e.code));this.listen(window,'blur',()=>{this.keys.clear();this.joystick={x:0,y:0}});
    this.frame=requestAnimationFrame(t=>this.tick(t));this.notice(config.intro);
  }
  listen(t,event,fn){t.addEventListener(event,fn);this.unsubs.push(()=>t.removeEventListener(event,fn))}
  obstacle(x,y,r){return this.walls.some(w=>x+r>w.x&&x-r<w.x+w.w&&y+r>w.y&&y-r<w.y+w.h)}
  move(dx,dy){const p=this.player,r=p.r,x=Math.max(r+14,Math.min(900-r-14,p.x+dx)),y=Math.max(r+14,Math.min(520-r-14,p.y+dy));if(!this.obstacle(x,p.y,r))p.x=x;if(!this.obstacle(p.x,y,r))p.y=y}
  available(o){return o.id==='gate'||o.id==='trader'||!this.config.flags.includes(o.id==='courier'?'courier':o.id)}
  nearest(){return this.objects.filter(o=>this.available(o)).sort((a,b)=>Math.hypot(a.x-this.player.x,a.y-this.player.y)-Math.hypot(b.x-this.player.x,b.y-this.player.y))[0]}
  interact(){if(!this.running||this.paused)return;const o=this.nearest();if(!o||Math.hypot(o.x-this.player.x,o.y-this.player.y)>66){this.notice('Move closer to a marked person, object, or gate.');return}this.hooks.onInteract?.(o.id)}
  notice(s){this.message=s;this.messageTime=4;this.hooks.onPrompt?.(s)}
  tick(t){if(!this.running)return;const dt=this.last?Math.min(.045,(t-this.last)/1000):0;this.last=t;this.elapsed+=dt;this.messageTime=Math.max(0,this.messageTime-dt);if(!this.paused){let dx=(this.keys.has('KeyD')||this.keys.has('ArrowRight')?1:0)-(this.keys.has('KeyA')||this.keys.has('ArrowLeft')?1:0)+this.joystick.x,dy=(this.keys.has('KeyS')||this.keys.has('ArrowDown')?1:0)-(this.keys.has('KeyW')||this.keys.has('ArrowUp')?1:0)+this.joystick.y;const n=Math.hypot(dx,dy);if(n>0){dx/=Math.max(1,n);dy/=Math.max(1,n);this.facing=Math.atan2(dy,dx);this.move(dx*195*dt,dy*195*dt)}this.saveTime+=dt;if(this.saveTime>1){this.saveTime=0;this.hooks.onMove?.(this.player)}}this.draw();this.frame=requestAnimationFrame(t=>this.tick(t))}
  draw(){const c=this.ctx,sector=this.sector;c.clearRect(0,0,900,520);const g=c.createLinearGradient(0,0,900,520);g.addColorStop(0,sector===0?'#344950':sector===1?'#4c4140':'#173e48');g.addColorStop(1,'#111c29');c.fillStyle=g;c.fillRect(0,0,900,520);const painted=window.BreakpointArt?.ground(c,sector);if(!painted){c.strokeStyle='#ffffff11';c.lineWidth=1;for(let x=0;x<900;x+=40){c.beginPath();c.moveTo(x,0);c.lineTo(x,520);c.stroke()}for(let y=0;y<520;y+=40){c.beginPath();c.moveTo(0,y);c.lineTo(900,y);c.stroke()}}
    c.fillStyle='#111d27';c.fillRect(0,0,900,20);c.fillRect(0,500,900,20);c.fillRect(0,0,20,520);c.fillRect(880,0,20,520);c.strokeStyle='#bfad7777';c.strokeRect(25,25,850,470);
    // Paths and buildings supply visual navigation without affecting collision.
    if(!painted){c.fillStyle='#d1bd8750';c.fillRect(50,235,810,42);c.fillStyle='#f2e2b426';for(let i=70;i<850;i+=70)c.fillRect(i,255,33,3)}
    for(const w of this.walls){if(window.BreakpointArt?.prop(c,'crate',w.x+w.w/2,w.y+w.h/2,w.w+10,w.h+10))continue;c.fillStyle='#111923';c.fillRect(w.x+7,w.y+8,w.w,w.h);c.fillStyle=sector===1?'#6c5d55':'#506671';c.fillRect(w.x,w.y,w.w,w.h);c.strokeStyle='#b6aa86';c.lineWidth=3;c.strokeRect(w.x,w.y,w.w,w.h);c.fillStyle='#ffffff19';c.fillRect(w.x+7,w.y+7,w.w-14,7)}
    for(const o of this.objects){if(!this.available(o))continue;const close=Math.hypot(o.x-this.player.x,o.y-this.player.y)<66,cx=o.x,cy=o.y;c.save();c.translate(cx,cy);c.fillStyle='#0008';c.beginPath();c.ellipse(0,13,28,10,0,0,Math.PI*2);c.fill();const sprite=o.type==='gate'?'gate':o.type==='terminal'?'terminal':o.id==='trader'?'trader':o.type==='crate'?(o.id==='beacon'||o.id==='component'||o.id==='core'?'beacon':'crate'):null;
      const drawn=o.id==='courier'?window.BreakpointArt?.actor(c,{x:0,y:0,phase:0},'player',-Math.PI/2,this.elapsed):sprite&&window.BreakpointArt?.prop(c,sprite,0,0,o.type==='gate'?52:o.id==='trader'?70:54,o.type==='gate'?100:o.id==='trader'?58:48);
      if(!drawn){if(o.type==='npc'){c.fillStyle=o.id==='courier'?'#b29f73':'#795d52';c.beginPath();c.arc(0,0,15,0,Math.PI*2);c.fill();c.fillStyle='#ddbf92';c.beginPath();c.arc(7,-2,7,0,Math.PI*2);c.fill();c.fillStyle='#333a42';c.fillRect(-10,-14,15,6)}else if(o.type==='gate'){c.strokeStyle=this.config.gateOpen?'#8be5e2':'#c77558';c.lineWidth=6;c.strokeRect(-21,-45,42,90);c.fillStyle=this.config.gateOpen?'#8be5e23d':'#1c252f';c.fillRect(-18,-41,36,82)}else if(o.type==='terminal'){c.fillStyle='#163947';c.fillRect(-17,-19,34,34);c.strokeStyle='#8be5e2';c.lineWidth=3;c.strokeRect(-17,-19,34,34);c.fillStyle='#84d9d2';c.fillRect(-10,-12,20,13)}else{c.fillStyle='#836b4c';c.fillRect(-19,-15,38,30);c.strokeStyle='#e0b777';c.lineWidth=3;c.strokeRect(-19,-15,38,30);c.beginPath();c.moveTo(-19,0);c.lineTo(19,0);c.stroke()}}
      if(o.type==='gate'&&!this.config.gateOpen){c.fillStyle='#0c1525aa';c.fillRect(-24,-47,48,94)}
      c.restore();this.label(c,cx,cy-(o.type==='gate'?64:38),`${o.label}${close?' · E':''}`,close?'#fff2ce':'#c9d1cc')}
    window.BreakpointArena.prototype.drawFighter.call(this,c,this.player,'player',this.facing);
    const near=this.nearest();if(near&&Math.hypot(near.x-this.player.x,near.y-this.player.y)<66)this.label(c,this.player.x,this.player.y-43,'INTERACT · E','#8be5e2');
    if(this.messageTime>0){c.fillStyle='#111b27e8';c.fillRect(195,23,510,41);c.strokeStyle='#e5bb75';c.strokeRect(195,23,510,41);this.label(c,450,49,this.message,'#f4f0e9')}
  }
  label(c,x,y,s,color){c.font='800 12px Arial';c.textAlign='center';const w=Math.min(500,c.measureText(s).width+18);c.fillStyle='#0a1523db';c.fillRect(x-w/2,y-15,w,22);c.fillStyle=color;c.fillText(s,x,y)}
  destroy(){this.running=false;cancelAnimationFrame(this.frame);for(const f of this.unsubs)f();this.unsubs=[]}
};
